/* ============ DOCX Export (Final v2 + Tracking) ============ */
document.getElementById('btnDoc').addEventListener('click', async () => {
  const d = window.__CF_LAST_DATA;
  if (!d) { alert('Pehle Step 7 mein preview generate karein.'); return; }
  const btn = document.getElementById('btnDoc');
  btn.disabled = true; btn.textContent = 'Generating…';
  try {
    const { Document, Packer, Paragraph, TextRun, ImageRun, HeadingLevel } = window.docx;
    const P = (text, o = {}) => new Paragraph({ children: [new TextRun({ text, bold: o.bold, size: o.size, color: o.color })], spacing: { after: o.after ?? 120 } });
    const H = t => new Paragraph({ text: t, heading: HeadingLevel.HEADING_2, spacing: { before: 220, after: 100 } });
    const row = (l, v) => v ? new Paragraph({ children: [new TextRun({ text: l + ': ', bold: true }), new TextRun({ text: v })], spacing: { after: 80 } }) : null;
    const add = (l, v) => { const r = row(l, v); if (r) children.push(r); };

    const children = [];
    children.push(new Paragraph({ children: [new TextRun({ text: 'CYBER CRIME EVIDENCE REPORT', bold: true, size: 32 })], spacing: { after: 160 } }));
    children.push(P('Case ID: ' + d.caseId + '   |   Generated: ' + d.date, { size: 20 }));

    children.push(H('Suspect Information'));
    add('Suspect / Accused Name', d.suspect.name); add('Primary Phone Number', d.suspect.phone);
    add('Alternative Number', d.suspect.alt); add('Payment Methods', d.suspect.pay);
    add('UPI ID', d.suspect.upi); add('Crypto Wallet Address', d.suspect.crypto);
    add('Instagram Username', d.suspect.insta); add('Telegram Username', d.suspect.tgUser);
    add('Telegram ID', d.suspect.tgId); add('Social Media Accounts', d.suspect.social);
    add('Other (Email / Website / App)', d.suspect.other);

    children.push(H('Crime Details'));
    add('Crime Type', d.crime.type); add('Platform Used', d.crime.platform);
    add('Date & Time of Incident', d.crime.date); add('Amount Lost', d.crime.amount);

    children.push(H('Description'));
    children.push(P(d.desc || '—'));

    children.push(H('Evidence'));
    if (!d.evidence.length) children.push(P('No evidence attached.'));
    for (let i = 0; i < d.evidence.length; i++) {
      const e = d.evidence[i];
      children.push(new Paragraph({ children: [new TextRun({ text: 'Exhibit ' + String.fromCharCode(65 + i) + ' · SHA-256: ' + e.hash.slice(0, 16) + '…', bold: true, size: 18 })], spacing: { after: 60 } }));
      try {
        const bin = atob(e.dataUrl.split(',')[1]);
        const bytes = new Uint8Array(bin.length);
        for (let j = 0; j < bin.length; j++) bytes[j] = bin.charCodeAt(j);
        const w = e.w || 600, h = e.h || 400;
        children.push(new Paragraph({ children: [new ImageRun({ type: 'png', data: bytes, transformation: { width: 420, height: Math.round(h * (420 / w)) } })], spacing: { after: 120 } }));
      } catch (err) {}
    }

    children.push(H('Officer Use'));
    children.push(row('Received By (Name / ID)', d.officer.received) || P('Received By (Name / ID): ____________________'));
    children.push(row('Station / Department / Unit', d.officer.station) || P('Station / Department / Unit: ____________________'));
    children.push(row('Case Status', d.officer.status) || P('Case Status: Open / Under Investigation / Closed'));
    if (d.officer.remarks) add('Officer Remarks', d.officer.remarks);
    children.push(P('Verification & Stamp: ____________________', { after: 80 }));

    children.push(H('Declaration'));
    children.push(P('Main ghoshna karta/karti hoon ki is report mein di gayi jankari meri jankari mein sach hai. Yeh report cyber cell / police mein submit karne hetu taiyar ki gayi hai.'));
    children.push(P('Complainant: ' + d.decl.name + (d.decl.contact ? ' · ' + d.decl.contact : '')));
    children.push(P('Signature: ____________________    Date: ____________________'));
    children.push(P(d.caseId + ' · Generated by CyberForce Case Report System · National Cyber Crime Helpline: 1930', { size: 16, color: '666666' }));

    const doc = new Document({ sections: [{ children }] });
    const blob = await Packer.toBlob(doc);
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = window.CF_CASE_ID + '-evidence-report.docx';
    a.click();
    if (window.saveReportMeta) saveReportMeta(d);
    if (window.CF_TRACK) CF_TRACK('export_docx', d.crime.type);
  } catch (e) { alert('DOC export failed: ' + e.message); }
  btn.disabled = false; btn.textContent = 'Download DOC';
});